import image1 from "../../ImageWomen/1.jpg"
import image2 from "../../ImageWomen/2.jpg"
import image3 from "../../ImageWomen/3.jpg"
import image4 from "../../ImageWomen/4.jpg"
import image5 from "../../ImageWomen/5.jpg"
import image6 from "../../ImageWomen/6.jpg"
import image7 from "../../ImageWomen/7.jpg"
import image8 from "../../ImageWomen/8.jpg"
import image9 from "../../ImageWomen/9.jpg"
import image10 from "../../ImageWomen/10.jpg"
import image11 from "../../ImageWomen/11.jpg"
import image12 from "../../ImageWomen/12.jpg"
import image13 from "../../ImageWomen/13.jpg"
import image14 from "../../ImageWomen/14.jpg"
import image15 from "../../ImageWomen/15.jpg"
import image16 from "../../ImageWomen/16.jpg"
import image17 from "../../ImageWomen/17.jpg"
import image18 from "../../ImageWomen/18.jpg"
import image19 from "../../ImageWomen/19.jpg"
import image20 from "../../ImageWomen/20.jpg"
import image21 from "../../ImageWomen/21.jpg"
import image22 from "../../ImageWomen/22.jpg"

export const initialSize = [
    {
        id: 1,
        name: 'sylvia',
        type: 'hamilton',
        image: image1,
        price: 2039000,
        oldprice: 2039000,
        quantity: 1,
        saleof: 15,
        size: 32,
    },
    {
        id: 2,
        name: 'lydia',
        type: 'hamilton',
        image: image2,
        price: 1724000,
        oldprice: 2299000,
        quantity: 1,
        saleof: 25,
        size: 32,
    },
    {
        id: 3,
        name: 'herbert',
        type: 'weimar',
        image: image3,
        price: 2039000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 25,
        size: 32,
    },
    {
        id: 4,
        name: 'sterling',
        type: 'weimar',
        image: image4,
        price: 2299000,
        oldprice: 2490000,
        quantity: 1,
        saleof: 20,
        size: 28,
    },
    {
        id: 5,
        name: 'kiss',
        type: 'moraine',
        image: image5,
        price: 1799000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 25,
        size: 28,
    },
    {
        id: 6,
        name: 'charm',
        type: 'moraine',
        image: image6,
        price: 1799000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 25,
        size: 28,
    },
    {
        id: 7,
        name: 'grace',
        type: 'moraine',
        image: image7,
        price: 1919000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 25,
        size: 28,
    },
    {
        id: 8,
        name: 'sky',
        type: 'melissani',
        image: image8,
        price: 1954000,
        oldprice: 2299000,
        quantity: 1,
        saleof: 20,
        size: 32,
    },
    {
        id: 9,
        name: 'haze',
        type: 'melissani',
        image: image9,
        price: 2039000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 15,
        size: 32,
    },
    {
        id: 10,
        name: 'dawn',
        type: 'melissani',
        image: image10,
        price: 1839050,
        oldprice: 2290000,
        quantity: 1,
        saleof: 20,
        size: 32,

    },
    {
        id: 11,
        name: 'dorothy',
        type: 'santorini',
        image: image11,
        price: 1819000,
        oldprice: 2599000,
        quantity: 1,
        saleof: 30,
        size: 24,
    },
    {
        id: 12,
        name: 'lace',
        type: 'moraine',
        image: image12,
        price: 1919000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 20,
        size: 28,
    },
    {
        id: 13,
        name: 'desire',
        type: 'moraine',
        image: image13,
        price: 1919000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 20,
        size: 28,
    },
    {
        id: 14,
        name: 'serene',
        type: 'melissani',
        image: image14,
        price: 2039000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 15,
        size: 32,
    },
    {
        id: 15,
        name: 'hera',
        type: 'santorini',
        image: image15,
        price: 1819000,
        oldprice: 2599000,
        quantity: 1,
        saleof: 30,
        size: 24,
    },
    {
        id: 16,
        name: 'scarlett',
        type: 'hamilton',
        image: image16,
        price: 1954000,
        oldprice: 2299000,
        quantity: 0,
        saleof: 0,
        size: 32,
    },
    {
        id: 17,
        name: 'anne',
        type: 'hamilton',
        image: image17,
        price: 2039000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 15,
        size: 32,
    },
    {
        id: 18,
        name: 'cora',
        type: 'hamilton',
        image: image18,
        price: 2039000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 15,
        size: 32,
    },
    {
        id: 19,
        name: 'tear',
        type: 'moraine',
        image: image19,
        price: 1919000,
        oldprice: 2399000,
        quantity: 1,
        size: 28,
        saleof: 20,
    },
    {
        id:20,
        name: 'loretta',
        type: 'hamilton',
        image: image20,
        price: 2039000,
        oldprice: 2399000,
        quantity: 1,
        saleof: 15,
        size: 32,
    },
    {
        id: 21,
        name: 'wind',
        type: 'melissani',
        image: image21,
        price: 2039000,
        oldprice: 2399000,
        quantity: 0,
        saleof: 0,
        size: 32,
    },
    {
        id: 22,
        name: 'fauna',
        type: 'santorini',
        image: image22,
        price: 1609000,
        oldprice: 2299000,
        quantity: 0,
        saleof: 0,
        size: 24,
    },
];