import image1 from "../../ImageAccessory/1.jpg"
import image2 from "../../ImageAccessory/2.jpg"
import image3 from "../../ImageAccessory/3.jpg"
import image4 from "../../ImageAccessory/4.jpg"
import image5 from "../../ImageAccessory/5.jpg"
import image6 from "../../ImageAccessory/6.jpg"
import image7 from "../../ImageAccessory/7.jpg"
import image8 from "../../ImageAccessory/8.jpg"
import image9 from "../../ImageAccessory/9.jpg"
import image10 from "../../ImageAccessory/10.jpg"
import image11 from "../../ImageAccessory/11.jpg"
import image12 from "../../ImageAccessory/12.jpg"
import image13 from "../../ImageAccessory/13.jpg"
import image14 from "../../ImageAccessory/14.jpg"
import image15 from "../../ImageAccessory/15.jpg"
import image16 from "../../ImageAccessory/16.jpg"
import image17 from "../../ImageAccessory/17.jpg"
import image18 from "../../ImageAccessory/18.jpg"
import image19 from "../../ImageAccessory/19.jpg"
import image20 from "../../ImageAccessory/20.jpg"
import image21 from "../../ImageAccessory/21.jpg"
import image22 from "../../ImageAccessory/22.jpg"
import image23 from "../../ImageAccessory/23.jpg"
import image24 from "../../ImageAccessory/24.jpg"
import image25 from "../../ImageAccessory/25.jpg"
import image26 from "../../ImageAccessory/26.jpg"
import image27 from "../../ImageAccessory/27.jpg"
import image28 from "../../ImageAccessory/28.jpg"
import image29 from "../../ImageAccessory/29.jpg"
import image30 from "../../ImageAccessory/30.jpg"
import image31 from "../../ImageAccessory/31.jpg"
import image32 from "../../ImageAccessory/32.jpg"
import image33 from "../../ImageAccessory/33.jpg"
import image34 from "../../ImageAccessory/34.jpg"
import image35 from "../../ImageAccessory/35.jpg"
import image36 from "../../ImageAccessory/36.jpg"
import image37 from "../../ImageAccessory/37.jpg"
import image38 from "../../ImageAccessory/38.jpg"
import image39 from "../../ImageAccessory/39.jpg"
import image40 from "../../ImageAccessory/40.jpg"
import image41 from "../../ImageAccessory/41.jpg"
import image42 from "../../ImageAccessory/42.jpg"
import image43 from "../../ImageAccessory/43.jpg"
import image44 from "../../ImageAccessory/44.jpg"
import image45 from "../../ImageAccessory/45.jpg"
import image46 from "../../ImageAccessory/46.jpg"

export const initialAccessoryComponent = [
    {
        id: 1,
        name: 'jackie gunmetal',
        type: 'vtnam',
        image: image1,
        price: 279000,
        oldprice: 399000,
        quantity: 1,
        saleof: 30,
        size: 144,
    },
    {
        id: 2,
        name: 'jackie silver',
        type: 'vtnam',
        image: image2,
        price: 279000,
        oldprice: 399000,
        quantity: 1,
        saleof: 30,
        size: 144,
        color: "silver",
    },
    {
        id: 3,
        name: 'jackie rosegold',
        type: 'vtnam',
        image: image3,
        price: 279000,
        oldprice: '399000',
        quantity: 1,
        saleof: 30,
        size: 144,
        color: "rosegold"
    },
    {
        id: 4,
        name: 'rosie silver rosegold',
        type: 'vtnam',
        image: image4,
        price: 279000,
        oldprice: 399000,
        quantity: 1,
        saleof: 30,
        size: 144,
        color: "rosegold"
    },
    {
        id: 5,
        name: 'rosie rosegold',
        type: 'pknu',
        image: image5,
        price: 279000,
        oldprice: 399000,
        quantity: 1,
        saleof: 30,
        size: 144,
        color: "rosegold",
    },
    {
        id: 6,
        name: 'rosie silver',
        type: 'pknu',
        image: image6,
        price: 279000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        saleof: 30,
        color: "silver",
    },
    {
        id: 7,
        name: 'stella silver',
        type: 'vtnam',
        image: image7,
        price: 279300,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        saleof: 30,
        color: "silver",
    },
    {
        id: 8,
        name: 'stella rosegold',
        type: 'vtnam',
        image: image8,
        price: 279000,
        oldprice: 399000,
        quantity: 1,
        saleof: 30,
        size: 144,
        color: "rosegold",
    },
    {
        id: 9,
        name: 'stella gunmetal',
        type: 'vtnam',
        image: image9,
        price: 279300,
        oldprice: 399000,
        size: 144,
        quantity: 1,
        saleof: 30,
    },
    {
        id: 10,
        name: 'cleo rosegold',
        type: 'pknu',
        image: image10,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        saleof: 30,
        color: "rosegold",
    },
    {
        id: 11,
        name: 'cleo silver',
        type: 'vtnu',
        image: image11,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        color: "sliver",
        size: 144,
        saleof: 20,
    },
    {
        id: 12,
        name: 'celia rosegold',
        type: 'pknu',
        image: image12,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        saleof: 20,
        size: 144,
        color: "rosegold",
    },
    {
        id: 13,
        name: 'celia silver',
        type: 'vtnu',
        image: image13,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        saleof: 20,
        size: 144,
        color: "silver",
    },
    {
        id: 14,
        name: 'doris rosegold',
        type: 'vtnu',
        image: image14,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        saleof: 20,
        color: "rosegold"
    },
    {
        id: 15,
        name: 'doris silver',
        type: 'vtnu',
        image: image15,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        color: "sliver",
        size: 144,
        saleof: 20,
    },
    {
        id: 16,
        name: 'cara grey',
        type: 'vtnu',
        image: image16,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        color: "grey",
        saleof: 20,
    },
    {
        id: 17,
        name: 'cara white',
        type: 'vtnu',
        image: image17,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        color: "white",
        size: 144,
        saleof: 20,
    },
    {
        id: 18,
        name: 'sarah white',
        type: 'vtnu',
        image: image18,
        price: 239200,
        oldprice: 299000,
        quantity: 1,
        saleof: 19,
        size: 144,
        color: "white"
    },
    {
        id: 19,
        name: 'sarah grey',
        type: 'vtnu',
        image: image19,
        price: 239200,
        oldprice: 299000,
        quantity: 1,
        size: 144,
        color: "grey",
        saleof: 19,
    },
    {
        id:20,
        name: 'gwen',
        type: 'vtnu',
        image: image20,
        price: 239000,
        oldprice: 299000,
        quantity: 1,
        saleof: 20,
        size: 144,
        color: "rosegold",
    },
    {
        id: 21,
        name: 'olivia silver',
        type: 'vtnu',
        image: image21,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        color: "sliver",
        saleof: 20,
        size: 144,
    },
    {
        id: 22,
        name: 'olivia rosegold',
        type: 'vtnu',
        image: image22,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        saleof: 20,
        color: "rosegold",
        size: 144,
    },
    {
        id: 23,
        name: 'clark silver',
        type: 'vtnam',
        image: image23,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        color: "black",
        saleof: 20,
    },
    {
        id: 24,
        name: 'clark gunmetal',
        type: 'vtnam',
        image: image24,
        price: 319000,
        oldprice: 399000,
        size: 144,
        quantity: 1,
        color: "black",
        saleof: 20,
    },
    {
        id: 25,
        name: 'ashton silver',
        type: 'vtnam',
        image: image25,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        saleof: 20,
        size: 144,
        color: "silver",
    },
    {
        id: 26,
        name: 'ashton gunmetal',
        type: 'vtnam',
        image: image26,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        color: "black",
        size: 144,
        saleof: 20,
    },
    {
        id: 27,
        name: 'tierra silver',
        type: 'vtnu',
        image: image27,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        color: "sliver",
        saleof: 20,
    },
    {
        id: 28,
        name: 'talia silver',
        type: 'vtnu',
        image: image28,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        color: "sliver",
        saleof: 20,
    },
    {
        id: 29,
        name: 'talia rosegold',
        type: 'vtnu',
        image: image29,
        price: 319000,
        size: 144,
        oldprice: 399000,
        quantity: 1,
        saleof: 20,
        color: "rosegold"
    },
    {
        id: 30,
        name: 'luna rosegold',
        type: 'vtnu',
        image: image30,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        color: "sliver",
        saleof: 20,
    },
    {
        id: 31,
        name: 'luna silver rosegold',
        type: 'vtnu',
        image: image31,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        saleof: 20,
        size: 144,
        color: "black",
    },
    {
        id: 32,
        name: 'hazel silver rosegold',
        type: 'vtnu',
        image: image32,
        price: 299000,
        oldprice: 399000,
        quantity: 1,
        color: "sliver",
        size: 144,
        saleof: 25,
    },
    {
        id: 33,
        name: 'hazel rosegold',
        type: 'vtnu',
        image: image33,
        price: 299000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        color: "sliver",
        saleof: 25,
    },
    {
        id: 34,
        name: 'amber rosegold',
        type: 'vtnu',
        image: image34,
        price: 339000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        saleof: 15,
        color: "rosegold",
    },
    {
        id: 35,
        name: 'amber silver rosegold',
        type: 'vtnu',
        image: image35,
        price: 339000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        color: "sliver",
        saleof: 15,
    },
    {
        id: 36,
        name: 'ivy rosegold',
        type: 'vtnu',
        image: image36,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        color: "rosegold",
        size: 144,
        saleof: 20,
    },
    {
        id: 37,
        name: 'ivy silver rosegold',
        type: 'vtnu',
        image: image37,
        price: 319000,
        oldprice: 399000,
        quantity: 1,
        size: 144,
        saleof: 20,
        color: "rosegold",
    },
];